name: portfolio
description: "My portfolio built with Jaspr."
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  jaspr: ^0.23.1
  jaspr_router: ^0.8.2
  web: ^1.1.1

dev_dependencies:
  jaspr_builder: ^0.23.1
  build_runner: ^2.4.8
  lints: ^3.0.0
  build_web_compilers: ^4.8.0

jaspr:
  mode: client
